# Generated by Django 4.2.1 on 2023-05-22 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='address',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
